data(iris)
names(iris)
table(iris$Species)
library(ggplot2)
qplot(Petal.Width, Sepal.Width, data = iris, colour = Species, size = I(4))
install.packages("tree")
library(tree)
tree1 <- tree(Species ~ Sepal.Width + Petal.Width, data = iris)
summary(tree1)
tree(formula = Species ~ Sepal.Width + Petal.Width, data = iris)
plot(tree1)
text(tree1)